micronaut:
  application:
    name: blockchain
  server:
    port: ${PORT:8080}

mqtt:
  client:
    server-uri: tcp://localhost:1883
    client-id: ${random.uuid}
jaga:
  blockchain:
    miner:
      prefixLength: ${PREFIX_LENGTH:3}